- hosts: localhost
  become: true
  roles:
  - python
  - docker
  - docker-compose
  tasks:
  - name: create git dir
    file:
      state: directory
      path: /home/edd-a/encounterproj
  - name: clone repo
    git:
      repo: https://github.com/QAEdd/encounterproj
      dest: /home/edd-a/encounterproj
      clone: yes
  vars:
    docker_user: qaedd

- hosts: ciservers
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: swarmmanagers
  become: true
  roles:
  - docker
  - swarm-manager
  tasks:
  - name: add ansible user to docker group
    user:
      name: qaedd
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworker
  become: true
  roles:
  - docker
  - swarm-worker
  vars:
    docker_user: qaedd